#!/usr/bin/env bash


_check_fs_btrfs() {
  local \
    _device="${1}"
  btrfs \
    check \
      "${_device}" 
}

_chroot_encrypted_open() {
  local \
    _device="${1}" \
    _fs_type="${2}" \
    _mount_point="${3}" \
    _paths=() \
    _cryptsetup_opts=() \
    _mount_opts=() \
    _mapper \
    _device_name
  _device_name="data"
  _mapper="/dev/mapper/${_device_name}" 
  _cryptsetup_opts+=(
    open
      "${_device}"
  )
  _mount_opts+=(
    -t
      "${fs_type}"
  )
  cryptsetup \
    "${_cryptsetup_opts[@]}" \
    "${_device_name}"
  "_check_fs_${fs_type}" \
    "/dev/mapper/${_device_name}" 
  mount \
    "${_mount_opts[@]}" \
  "/dev/mapper/${_device_name}" \
  "${_mount_point}"
}

if (( 0 < "${#}" )); then
  chroot_path="${1}"
else
  chroot_path="$(pwd)"
fi
fs_type="btrfs"
if (( 1 < "${#}" )); then
  fs_type="${2}"
fi
mount_point="/mnt"
if (( 2 < "${#}" )); then
  mount_point="${3}"
fi

app_opts=(
  "${chroot_path}"
  "${fs_type}"
  "${mount_point}"
)

_chroot_encrypted_open \
  "${app_opts[@]}"
