#!/usr/bin/env bash

#    ----------------------------------------------------------------------
#    Copyright © 2025, 2026  Pellegrino Prevete
#
#    All rights reserved
#    ----------------------------------------------------------------------
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

_startx() {
  local \
    _user="${1}" \
    _tty="${2}" \
    _cmd=() \
    _msg=()
  if (( EUID == 0 )); then
    _msg=(
      "${app_name} must be run as user."
    )
    echo \
      "${_msg[*]}"
    return \
      1
  fi
  _cmd+=(
    "startx"
  )
  su \
    -c \
      "${_cmd[*]}" - \
    user &
}

_components_start_delayed() {
  local \
    _sleep="${1}"
  sleep \
    "${_sleep}"
  xfwm4 \
    --replace &
  xfwm4-panel &
}

_graphical_environment_start() {
  local \
    _user="${1}" \
    _tty="${2}" \
    _display=0
  export \
    DISPLAY="${_display}"
  _startx \
    "${_user}" \
    "${_tty}"
  _components_start_delayed \
    "15"
}

target_user="user"
if (( 0 < "${#}" )); then
  target_user="${1}"
fi
target_tty="/dev/tty0"
if (( 1 < "${#}" )); then
  target_tty="${2}"
fi

app_opts=(
  "${target_user}"
  "${target_tty}"
)

_graphical_environment_start \
  "${app_opts[@]}"
