#!/usr/bin/env bash


_graphical_environment_runtime_setup() {
  local \
    _chroot="${1}" \
    _paths=()
  _paths+=(
    '/run/dbus'
    '/run/udev'
  )
  for _path in "${_paths[@]}"; do
    mount \
      -o \
        bind \
      "${_paths}" \
      "${_chroot}${_path}"
  done
}

chroot_path="/mnt"
if (( 0 < "${#}" )); then
  chroot_path="${1}"
fi

app_opts=(
  "${chroot_path}"
)

_graphical_environment_runtime_setup \
  "${app_opts[@]}"
